name: apply
on:
  workflow_call:
    inputs:
      github:
        description: The caller's github context.
        required: true
        type: string
      workspace:
        description: The caller's github workspace.
        required: true
        type: string
      type:
        description: Which plan job to run.
        required: true
        type: string
      variables:
        description: 'A json string of variables to pass to terraform. This will be written as terraform.tfvars.json file, please see https://developer.hashicorp.com/terraform/language/values/variables#variable-definitions-tfvars-files.'
        required: false
        type: string
    outputs:
      apply_project_access:
        description: The output from the job.
        value: ${{jobs.apply_project_access.outputs > 0 && fromJSON(jobs.apply_project_access.outputs.output || '{}')}}
      apply_ci_access:
        description: The output from the job.
        value: ${{jobs.apply_ci_access.outputs > 0 && fromJSON(jobs.apply_ci_access.outputs.output) || '{}'}}
      apply_prototype:
        description: The output from the job.
        value: ${{jobs.apply_prototype.outputs > 0 && fromJSON(jobs.apply_prototype.outputs.output) || '{}'}}
      apply_servers:
        description: The output from the job.
        value: ${{jobs.apply_servers.outputs > 0 && fromJSON(jobs.apply_servers.outputs.output) || '{}'}}
      apply_skip:
        description: The output from the job.
        value: ${{jobs.apply_skip.outputs > 0 && fromJSON(jobs.apply_skip.outputs.output) || '{}'}}

permissions: write-all

jobs:
  apply_project_access:
    uses: ./.github/workflows/reusable-apply.yaml
    if: inputs.type == 'phase_1_project_access'
    with:
      aws-auth-type: ${{vars.AWS_AUTH}}
      repository: ${{fromJSON(inputs.github).repository}}
      workspace: ${{inputs.workspace}}
      directory: ${{inputs.type}}
      run-id: ${{fromJSON(inputs.github).run_id}}
      variables: ${{inputs.variables}}
    secrets:
      aws-region: ${{secrets.AWS_REGION}}
      aws-role: ${{secrets.AWS_ROLE}}
      aws-session: ${{fromJSON(inputs.github).job}}-${{fromJSON(inputs.github).run_id}}-${{fromJSON(inputs.github).run_number}}-${{fromJSON(inputs.github).run_attempt}}
      aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
      aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
      github-token: ${{secrets.GITHUB_TOKEN}}
      age-secret-key: ${{secrets.AGE_SECRET_KEY}}

  apply_ci_access:
    uses: ./.github/workflows/reusable-apply.yaml
    if: inputs.type == 'phase_2_ci_access'
    with:
      aws-auth-type: ${{vars.AWS_AUTH}}
      repository: ${{fromJSON(inputs.github).repository}}
      workspace: ${{inputs.workspace}}
      directory: ${{inputs.type}}
      run-id: ${{fromJSON(inputs.github).run_id}}
      variables: ${{inputs.variables}}
    secrets:
      aws-region: ${{secrets.AWS_REGION}}
      aws-role: ${{secrets.AWS_ROLE}}
      aws-session: ${{fromJSON(inputs.github).job}}-${{fromJSON(inputs.github).run_id}}-${{fromJSON(inputs.github).run_number}}-${{fromJSON(inputs.github).run_attempt}}
      aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
      aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
      github-token: ${{secrets.GITHUB_TOKEN}}
      age-secret-key: ${{secrets.AGE_SECRET_KEY}}

  apply_prototype:
    uses: ./.github/workflows/reusable-apply.yaml
    if: inputs.type == 'phase_3_prototype'
    with:
      aws-auth-type: ${{vars.AWS_AUTH}}
      repository: ${{fromJSON(inputs.github).repository}}
      workspace: ${{inputs.workspace}}
      directory: ${{inputs.type}}
      run-id: ${{fromJSON(inputs.github).run_id}}
      variables: ${{inputs.variables}}
    secrets:
      aws-region: ${{secrets.AWS_REGION}}
      aws-role: ${{secrets.AWS_ROLE}}
      aws-session: ${{fromJSON(inputs.github).job}}-${{fromJSON(inputs.github).run_id}}-${{fromJSON(inputs.github).run_number}}-${{fromJSON(inputs.github).run_attempt}}
      aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
      aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
      github-token: ${{secrets.GITHUB_TOKEN}}
      age-secret-key: ${{secrets.AGE_SECRET_KEY}}

  apply_servers:
    uses: ./.github/workflows/reusable-apply.yaml
    if: inputs.type == 'phase_4_servers'
    with:
      aws-auth-type: ${{vars.AWS_AUTH}}
      repository: ${{fromJSON(inputs.github).repository}}
      workspace: ${{inputs.workspace}}
      directory: ${{inputs.type}}
      run-id: ${{fromJSON(inputs.github).run_id}}
      variables: ${{inputs.variables}}
    secrets:
      aws-region: ${{secrets.AWS_REGION}}
      aws-role: ${{secrets.AWS_ROLE}}
      aws-session: ${{fromJSON(inputs.github).job}}-${{fromJSON(inputs.github).run_id}}-${{fromJSON(inputs.github).run_number}}-${{fromJSON(inputs.github).run_attempt}}
      aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
      aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
      github-token: ${{secrets.GITHUB_TOKEN}}
      age-secret-key: ${{secrets.AGE_SECRET_KEY}}

  apply_skip:
    runs-on: ubuntu-latest
    if: inputs.type == 'skip'
    outputs:
      output: steps.out.outputs.output
    steps:
      - name: out
        id: out
        run: echo "output={}" >> "$GITHUB_OUTPUT"