name: destroy
# WARNING! This workflow destroys infrastructure!
# WARNING! Servers depend on prototype! (they must exist, but don't need to be on)
#  - this is because servers AMI is a pointer to a Prototype snapshot which has thin copy of a Prototype volume's base image

on:
  workflow_call:
    inputs:
      github:
        description: The caller's github context.
        required: true
        type: string
      workspace:
        description: The caller's github workspace.
        required: true
        type: string
      type:
        description: Which plan job to run.
        required: true
        type: string
      variables:
        description: 'A json string of variables to pass to terraform. This will be written as terraform.tfvars.json file, please see https://developer.hashicorp.com/terraform/language/values/variables#variable-definitions-tfvars-files.'
        required: false
        type: string

permissions: write-all

jobs:
  destroy_project_access:
    uses: ./.github/workflows/reusable-destroy.yaml
    if: inputs.type == 'phase_1_project_access'
    with:
      aws-auth-type: ${{vars.AWS_AUTH}}
      repository: ${{fromJSON(inputs.github).repository}}
      workspace: ${{inputs.workspace}}
      directory: ${{inputs.type}}
      run-id: ${{fromJSON(inputs.github).run_id}}
      variables: ${{inputs.variables}}
    secrets:
      aws-region: ${{secrets.AWS_REGION}}
      aws-role: ${{secrets.AWS_ROLE}}
      aws-session: ${{fromJSON(inputs.github).job}}-${{fromJSON(inputs.github).run_id}}-${{fromJSON(inputs.github).run_number}}-${{fromJSON(inputs.github).run_attempt}}
      aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
      aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
      github-token: ${{secrets.GITHUB_TOKEN}}
      age-secret-key: ${{secrets.AGE_SECRET_KEY}}

  destroy_ci_access:
    uses: ./.github/workflows/reusable-destroy.yaml
    if: inputs.type == 'phase_2_ci_access'
    with:
      aws-auth-type: ${{vars.AWS_AUTH}}
      repository: ${{fromJSON(inputs.github).repository}}
      workspace: ${{inputs.workspace}}
      directory: ${{inputs.type}}
      run-id: ${{fromJSON(inputs.github).run_id}}
      variables: ${{inputs.variables}}
    secrets:
      aws-region: ${{secrets.AWS_REGION}}
      aws-role: ${{secrets.AWS_ROLE}}
      aws-session: ${{fromJSON(inputs.github).job}}-${{fromJSON(inputs.github).run_id}}-${{fromJSON(inputs.github).run_number}}-${{fromJSON(inputs.github).run_attempt}}
      aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
      aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
      github-token: ${{secrets.GITHUB_TOKEN}}
      age-secret-key: ${{secrets.AGE_SECRET_KEY}}

  destroy_prototype:
    uses: ./.github/workflows/reusable-destroy.yaml
    if: inputs.type == 'phase_3_prototype'
    with:
      aws-auth-type: ${{vars.AWS_AUTH}}
      repository: ${{fromJSON(inputs.github).repository}}
      workspace: ${{inputs.workspace}}
      directory: ${{inputs.type}}
      run-id: ${{fromJSON(inputs.github).run_id}}
      variables: ${{inputs.variables}}
    secrets:
      aws-region: ${{secrets.AWS_REGION}}
      aws-role: ${{secrets.AWS_ROLE}}
      aws-session: ${{fromJSON(inputs.github).job}}-${{fromJSON(inputs.github).run_id}}-${{fromJSON(inputs.github).run_number}}-${{fromJSON(inputs.github).run_attempt}}
      aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
      aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
      github-token: ${{secrets.GITHUB_TOKEN}}
      age-secret-key: ${{secrets.AGE_SECRET_KEY}}

  destroy_servers:
    uses: ./.github/workflows/reusable-destroy.yaml
    if: inputs.type == 'phase_4_servers'
    with:
      aws-auth-type: ${{vars.AWS_AUTH}}
      repository: ${{fromJSON(inputs.github).repository}}
      workspace: ${{inputs.workspace}}
      directory: ${{inputs.type}}
      run-id: ${{fromJSON(inputs.github).run_id}}
      variables: ${{inputs.variables}}
    secrets:
      aws-region: ${{secrets.AWS_REGION}}
      aws-role: ${{secrets.AWS_ROLE}}
      aws-session: ${{fromJSON(inputs.github).job}}-${{fromJSON(inputs.github).run_id}}-${{fromJSON(inputs.github).run_number}}-${{fromJSON(inputs.github).run_attempt}}
      aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
      aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
      github-token: ${{secrets.GITHUB_TOKEN}}
      age-secret-key: ${{secrets.AGE_SECRET_KEY}}

  destroy_skip:
    runs-on: ubuntu-latest
    if: inputs.type == 'skip'
    steps:
      - run: echo 'skipping destroy step...'
