name: plan
on:
  workflow_call:
    inputs:
      github:
        description: The caller's github context.
        required: true
        type: string
      workspace:
        description: The caller's github workspace.
        required: true
        type: string
      ignore_error:
        description: When true errors from this job will be ignored.
        required: false
        type: boolean
        default: false
      type:
        description: Which plan job to run.
        required: true
        type: string
      variables:
        description: 'A json string of variables to pass to terraform. This will be written as terraform.tfvars.json file, please see https://developer.hashicorp.com/terraform/language/values/variables#variable-definitions-tfvars-files.'
        required: false
        type: string

permissions: write-all

jobs:
  get_runner_ip:
    runs-on: ubuntu-latest
    outputs:
      ip: ${{steps.ip.outputs.ipv4}}
    steps:
      - uses: haythem/public-ip@v1.3
        id: ip

  plan_project_access:
    uses: ./.github/workflows/reusable-plan.yaml
    if: inputs.type == 'phase_1_project_access'
    with:
      aws-auth-type: ${{vars.AWS_AUTH}}
      repository: ${{fromJson(inputs.github).repository}}
      workspace: ${{inputs.workspace}}
      directory: ${{inputs.type}}
      run-id: ${{fromJson(inputs.github).run_id}}
      ignore_error: ${{inputs.ignore_error}}
      variables: ${{inputs.variables}}
    secrets:
      aws-region: ${{secrets.AWS_REGION}}
      aws-role: ${{secrets.AWS_ROLE}}
      aws-session: ${{fromJson(inputs.github).job}}-${{fromJson(inputs.github).run_id}}-${{fromJson(inputs.github).run_number}}-${{fromJson(inputs.github).run_attempt}}
      aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
      aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
      github-token: ${{secrets.GITHUB_TOKEN}}
      age-secret-key: ${{secrets.AGE_SECRET_KEY}}

  plan_ci_access:
    uses: ./.github/workflows/reusable-plan.yaml
    needs: get_runner_ip
    if: inputs.type == 'phase_2_ci_access'
    with:
      aws-auth-type: ${{vars.AWS_AUTH}}
      repository: ${{fromJson(inputs.github).repository}}
      workspace: ${{inputs.workspace}}
      directory: ${{inputs.type}}
      run-id: ${{fromJson(inputs.github).run_id}}
      ignore_error: ${{inputs.ignore_error}}
      variables: ${{inputs.variables}}
    secrets:
      aws-region: ${{secrets.AWS_REGION}}
      aws-role: ${{secrets.AWS_ROLE}}
      aws-session: ${{fromJson(inputs.github).job}}-${{fromJson(inputs.github).run_id}}-${{fromJson(inputs.github).run_number}}-${{fromJson(inputs.github).run_attempt}}
      aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
      aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
      github-token: ${{secrets.GITHUB_TOKEN}}
      age-secret-key: ${{secrets.AGE_SECRET_KEY}}

  plan_prototype:
    uses: ./.github/workflows/reusable-plan.yaml
    if: inputs.type == 'phase_3_prototype'
    with:
      aws-auth-type: ${{vars.AWS_AUTH}}
      repository: ${{fromJson(inputs.github).repository}}
      workspace: ${{inputs.workspace}}
      directory: ${{inputs.type}}
      run-id: ${{fromJson(inputs.github).run_id}}
      ignore_error: ${{inputs.ignore_error}}
      variables: ${{inputs.variables}}
    secrets:
      aws-region: ${{secrets.AWS_REGION}}
      aws-role: ${{secrets.AWS_ROLE}}
      aws-session: ${{fromJson(inputs.github).job}}-${{fromJson(inputs.github).run_id}}-${{fromJson(inputs.github).run_number}}-${{fromJson(inputs.github).run_attempt}}
      aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
      aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
      github-token: ${{secrets.GITHUB_TOKEN}}
      age-secret-key: ${{secrets.AGE_SECRET_KEY}}

  plan_servers:
    uses: ./.github/workflows/reusable-plan.yaml
    if: inputs.type == 'phase_4_servers'
    with:
      aws-auth-type: ${{vars.AWS_AUTH}}
      repository: ${{fromJson(inputs.github).repository}}
      workspace: ${{inputs.workspace}}
      directory: ${{inputs.type}}
      run-id: ${{fromJson(inputs.github).run_id}}
      ignore_error: ${{inputs.ignore_error}}
      variables: ${{inputs.variables}}
    secrets:
      aws-region: ${{secrets.AWS_REGION}}
      aws-role: ${{secrets.AWS_ROLE}}
      aws-session: ${{fromJson(inputs.github).job}}-${{fromJson(inputs.github).run_id}}-${{fromJson(inputs.github).run_number}}-${{fromJson(inputs.github).run_attempt}}
      aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
      aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
      github-token: ${{secrets.GITHUB_TOKEN}}
      age-secret-key: ${{secrets.AGE_SECRET_KEY}}