name: Release

on:
  push:
    branches:
    - main

env:
  AWS_REGION: us-west-1
  TERRAFORM_VERSION: 1.5.7
  AWS_ROLE: arn:aws:iam::270074865685:role/terraform-module-ci-test

permissions:
  id-token: write
  contents: write
  pull-requests: write
  issues: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release-please
        with:
          release-type: terraform-module
          pull-request-title-pattern: "chore${scope}: release${component} ${version}"
      - name: 'Remind to Review Plan'
        uses: peter-evans/create-or-update-comment@v3
        if: steps.release-please.outputs.pr
        with:
          issue-number: ${{ fromJson(steps.release-please.outputs.pr).number }}
          body: |
            Please make sure to review the plan before merging this PR!
            ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
      - uses: actions/checkout@v4
        if: steps.release-please.outputs.pr
      - uses: DeterminateSystems/nix-installer-action@main
        if: steps.release-please.outputs.pr
      - uses: DeterminateSystems/magic-nix-cache-action@main
        if: steps.release-please.outputs.pr
      - uses: nicknovitski/nix-develop@v1
        if: steps.release-please.outputs.pr
      - uses: aws-actions/configure-aws-credentials@v4
        if: steps.release-please.outputs.pr
        with:
          role-to-assume: ${{env.AWS_ROLE}}
          role-session-name: ${{github.job}}-${{github.run_id}}-${{github.run_number}}-${{github.run_attempt}}
          aws-region: ${{env.AWS_REGION}}
      - name: 'Config Terraform plugin cache'
        if: steps.release-please.outputs.pr
        run: |
          echo 'plugin_cache_dir="$HOME/.terraform.d/plugin-cache"' >~/.terraformrc
          mkdir --parents ~/.terraform.d/plugin-cache
      - name: Cache Terraform
        uses: actions/cache@v3
        if: steps.release-please.outputs.pr
        with:
          path: |
            ~/.terraform.d/plugin-cache
          key: ${{ runner.os }}-terraform-${{ hashFiles('**/.terraform.lock.hcl') }}
          restore-keys: |
            ${{ runner.os }}-terraform-
      - name: 'Show Plan'
        id: terraform-plan
        if: steps.release-please.outputs.pr
        run: |
          echo '${{secrets.AGE_SECRET_KEY}}' | age -d -i - -o terraform.tfstate terraform.tfstate.age
          terraform init
          rm -f plan.tfplan
          echo '```' > plan.tfplan
          echo '# terraform plan -input=false -no-color' >> plan.tfplan
          terraform plan -input=false -no-color >> plan.tfplan
          echo '```' >> plan.tfplan
          rm -f terraform.tfstate
      - name: 'Add plan to PR'
        uses: peter-evans/create-or-update-comment@v3
        if: steps.release-please.outputs.pr
        with:
          issue-number: ${{ fromJson(steps.release-please.outputs.pr).number }}
          body-path: ./plan.tfplan
