name: release

on:
  push:
    branches:
    - main

env:
  AWS_REGION: us-west-1
  AWS_ROLE: arn:aws:iam::270074865685:role/terraform-module-ci-test
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
  GITHUB_OWNER: ${{ github.repository_owner }}

permissions: write-all

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v4
        id: release-please
        with:
          release-type: terraform-module
      - uses: actions/checkout@v4
      # try to blackhole upstream cache
#      - run: echo '127.0.0.1 cache.nixos.org' >> /etc/hosts
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
        with:
          upstream-cache: null
      - uses: nicknovitski/nix-develop@v1.1.0
        with:
          arguments: |
            --ignore-environment \
            --extra-experimental-features nix-command \
            --extra-experimental-features flakes \
            --keep HOME \
            --keep SSH_AUTH_SOCK \
            --keep GITHUB_TOKEN \
            --keep AWS_ROLE \
            --keep AWS_REGION \
            --keep AWS_DEFAULT_REGION \
            --keep AWS_ACCESS_KEY_ID \
            --keep AWS_SECRET_ACCESS_KEY \
            --keep AWS_SESSION_TOKEN \
            --keep TERM \
            ${{ github.workspace }}
      - uses: actions/cache/restore@v3
        id: cache-terraform-restore
        with:
          path: ${{ github.workspace }}/.terraform
          key: terraform-${{hashFiles('**/versions.tf','**/main.tf')}}
      - run: terraform init -upgrade
      - uses: actions/cache/save@v3
        id: cache-terraform-save
        with:
          path: ${{ github.workspace }}/.terraform
          key: ${{ steps.cache-terraform-restore.outputs.cache-primary-key }}
# only run after release is created
      - uses: aws-actions/configure-aws-credentials@v4
        if: steps.release-please.outputs.release_created
        with:
          role-to-assume: ${{env.AWS_ROLE}}
          role-session-name: ${{github.job}}-${{github.run_id}}-${{github.run_number}}-${{github.run_attempt}}
          aws-region: ${{env.AWS_REGION}}
      - uses: haythem/public-ip@v1.3
        id: ip
        if: steps.release-please.outputs.release_created
      - name: Apply
        if: steps.release-please.outputs.release_created
        shell: bash
        run: |
          set -e
          # generate age key if not found
          AGE_PUBLIC_KEY="${{secrets.AGE_PUBLIC_KEY}}"
          if [ "" = "${{secrets.AGE_SECRET_KEY}}" ]; then
            echo "Age key not found, adding one for CI"
            age-keygen -o age_key.txt
            gh secret set AGE_SECRET_KEY --body "$(cat age_key.txt)" --visibility repo
            gh secret set AGE_PUBLIC_KEY --body "$(age-keygen -y age_key.txt)" --visibility repo
            AGE_PUBLIC_KEY="$(age-keygen -y age_key.txt)"
            rm -f age_key.txt
          fi
          # generate recipients if not found
          if [ ! -f age_recipients.txt ]; then
            echo "Generating age_recipients.txt, you will need to add your personal public age key to this file to access secrets"
            touch age_recipients.txt
          fi
          # add ci recipient to list if not found
          if [ "" = "$(grep "$AGE_PUBLIC_KEY" age_recipients.txt)" ]; then
              echo "# CI" >> age_recipients.txt
              echo "$AGE_PUBLIC_KEY" >> age_recipients.txt
          fi
          # generate encrypted ssh key if not found
          if [ ! -f ssh_key ]; then
            echo "encrypted ssh key not found, generating one"
            # uses rsa due to STIG images not accepting anything else
            rm -f ssh_key.pub
            ssh-keygen -N "" -t rsa -b 4096 -C "${{github.repository}}" -f ssh_key
            chmod 0600 ssh_key
            age -e -R age_recipients.txt -o ssh.age ssh_key && rm -f ssh_key
          fi
          eval "$(ssh-agent -s)"
          echo '${{secrets.AGE_SECRET_KEY}}' | age -d -i - -o ssh_key ssh.age
          chmod 0600 ssh_key
          ssh-add ssh_key
          if [ ! -f terraform.tfstate.age ]; then
            echo "no state found, is this the first run?"
            echo "generating initial state"
            if [ ! -f terraform.tfstate ]; then touch terraform.tfstate; fi;
            age -e -R age_recipients.txt -o terraform.tfstate.age terraform.tfstate && rm -rf terraform.tfstate
          fi
          echo '${{secrets.AGE_SECRET_KEY}}' | age -d -i - -o terraform.tfstate terraform.tfstate.age
          export TF_VAR_ip="${{ steps.ip.outputs.ipv4 }}"
          terraform init
          # manage the security group rule for the terraform runner as a separate entity to prevent dependency chain issues with server object
          terraform apply --auto-approve -target=module.aws_rke2_rhel9_rpm.module.aws_access.module.security_group.aws_vpc_security_group_egress_rule.to_ip[0] || true
          terraform apply --auto-approve -target=module.aws_rke2_rhel9_rpm.module.aws_access.module.security_group.aws_vpc_security_group_ingress_rule.from_ip[0] || true
          terraform apply --auto-approve || true
          terraform apply --auto-approve || true
          rm -rf ssh_key
          rm -rf age_key.txt
          rm -rf terraform.tfstate.age
          age -e -R age_recipients.txt -o terraform.tfstate.age terraform.tfstate
          rm -f terraform.tfstate
          git config --global user.name 'automation'
          git config --global user.email 'automation@users.noreply.github.com'
          git remote set-url origin "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{github.repository}}"
          git add terraform.tfstate.age
          git add age_recipients.txt
          git add ssh_key.pub
          git add ssh.age
          git commit -s -m "New State ${{github.job}}-${{github.run_id}}-${{github.run_number}}-${{github.run_attempt}}"
          git push origin main
