name: rotate-ci-age-key

on:
  schedule:
    # Runs at 12PM UTC on Mondays
    - cron: '0 12 * * 1'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions: write-all

env:
  GITHUB_TOKEN: ${{ secrets.ADMIN_GITHUB_TOKEN }}
  GH_TOKEN: ${{ secrets.ADMIN_GITHUB_TOKEN }}

jobs:
  rotate-ci-age-key:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: nicknovitski/nix-develop@v1.1.0
        with:
          arguments: |
            --ignore-environment \
            --extra-experimental-features nix-command \
            --extra-experimental-features flakes \
            --keep HOME \
            --keep SSH_AUTH_SOCK \
            --keep GITHUB_TOKEN \
            --keep AWS_ROLE \
            --keep AWS_REGION \
            --keep AWS_DEFAULT_REGION \
            --keep AWS_ACCESS_KEY_ID \
            --keep AWS_SECRET_ACCESS_KEY \
            --keep AWS_SESSION_TOKEN \
            --keep TERM \
            ${{ github.workspace }}
      - name: 'Rotate CI AGE Key'
        run: |
          echo "Rotating AGE key for the CI..."
          if [ -z "$GITHUB_TOKEN" ]; then echo "token not found, please make sure to add ADMIN_GITHUB_TOKEN to secrets"; exit 1; fi
          if [ "" = '${{secrets.AGE_SECRET_KEY}}' ]; then echo "Missing encrypt key."; exit 1; fi

          echo "Decrypt files..."
          while read -r file; do
            echo '${{secrets.AGE_SECRET_KEY}}' | age -d -i - -o "$file" "$file.age"
          done <secret_file_list.txt

          echo "Remove old key..."
          OLD_PUB_KEY="$(echo '${{secrets.AGE_SECRET_KEY}}' | age-keygen -y)"
          grep -v "$OLD_PUB_KEY" age_recipients.txt > new_age_recipients.txt
          mv new_age_recipients.txt age_recipients.txt
          
          echo "Generate new key..."
          KEY="$(age-keygen 2>/dev/null | grep '^AGE')"
          echo "$KEY" | age-keygen -y >> age_recipients.txt
          gh secret set AGE_SECRET_KEY --body "$KEY"

          echo "Re-encrypt files..."
          while read -r file; do
            rm -f "$file.age"
            age -e -R age_recipients.txt -o "$file.age" "$file"
            rm -f "$file"
          done <secret_file_list.txt

          echo "Save files under new encryption..."
          git config --global user.name 'automation'
          git config --global user.email 'automation@users.noreply.github.com'
          git remote set-url origin "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{github.repository}}"
          while read -r file; do
            git add "$file.age";
          done <secret_file_list.txt
          git add age_recipients.txt
          git commit -s -m "Rotate AGE key https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}"
          git push origin main
