name: Tests

on:
  pull_request:
    branches:
    - main

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: DeterminateSystems/nix-installer-action@main
    - name: 'Restore Nix Store Cache'
      id: cache-nix-store-restore
      uses: actions/cache/restore@v3
      with:
        path: /nix/store
        key: nix-store
    - uses: nicknovitski/nix-develop@v1
    - name: 'Cache Nix Store'
      id: cache-nix-store-save
      uses: actions/cache/save@v3
      with:
        path: /nix/store
        key: ${{ steps.cache-nix-store-restore.outputs.cache-primary-key }}
    - run: terraform version
    - uses: haythem/public-ip@v1.3
      id: ip
    - name: 'Restore Terraform Cache'
      id: cache-terraform-restore
      uses: actions/cache/restore@v3
      with:
        path: ./.terraform
        key: terraform
    - run: terraform init
    - name: 'Cache Terraform'
      id: cache-terraform-save
      uses: actions/cache/save@v3
      with:
        path: ./.terraform
        key: ${{ steps.cache-terraform-restore.outputs.cache-primary-key }}
    - run: terraform init && terraform validate
      env:
        TF_VAR_ip: ${{ steps.ip.outputs.ipv4 }}

  tflint:
    name: 'TFLint'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: terraform-linters/setup-tflint@v4
      with:
        tflint_version: latest
    - run: tflint --version
    - run: tflint --init
    - run: tflint -f compact

  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ludeeus/action-shellcheck@master

  validate-commit-message:
    name: Validate Commit Message
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.LIMITED_GITHUB_TOKEN }}
